spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boke?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    drive-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
